INSERT INTO booking_details (booking_id, transaction_type, booking_mode, bus_number, schedule_id, route_id, child, adult) VALUES (1001, 'Paytm', 'C', 1, 201, 1, 0, 3);
INSERT INTO booking_details (booking_id, transaction_type, booking_mode, bus_number, schedule_id, route_id, child, adult) VALUES (1002, 'Netbanking', 'A', 6, 220, 4, 1, 2);
INSERT INTO booking_details (booking_id, transaction_type, booking_mode, bus_number, schedule_id, route_id, child, adult) VALUES (1003, 'Credit Card', 'C', 5, 214, 13, 2, 2);
INSERT INTO booking_details (booking_id, transaction_type, booking_mode, bus_number, schedule_id, route_id, child, adult) VALUES (1004, 'Cash', 'C', 2, 209, 20, 2, 3);
INSERT INTO booking_details (booking_id, transaction_type, booking_mode, bus_number, schedule_id, route_id, child, adult) VALUES (1005, 'Debit Card', 'C', 7, 224, 23, 1, 3);
INSERT INTO booking_details (booking_id, transaction_type, booking_mode, bus_number, schedule_id, route_id, child, adult) VALUES (1006, 'Cash', 'A', 1, 203, 3, 1, 2);
INSERT INTO booking_details (booking_id, transaction_type, booking_mode, bus_number, schedule_id, route_id, child, adult) VALUES (1007, 'Credit Card', 'A', 9, 230, 14, 0, 2);
INSERT INTO booking_details (booking_id, transaction_type, booking_mode, bus_number, schedule_id, route_id, child, adult) VALUES (1008, 'Cash', 'A', 10, 231, 16, 0, 3);
INSERT INTO booking_details (booking_id, transaction_type, booking_mode, bus_number, schedule_id, route_id, child, adult) VALUES (1009, 'Cash', 'C', 1, 204, 20, 1, 3);
INSERT INTO booking_details (booking_id, transaction_type, booking_mode, bus_number, schedule_id, route_id, child, adult) VALUES (1010, 'Debit Card', 'A', 5, 215, 15, 0, 3);
INSERT INTO booking_details (booking_id, transaction_type, booking_mode, bus_number, schedule_id, route_id, child, adult) VALUES (1011, 'Paytm', 'A', 3, 212, 5, 1, 1);
INSERT INTO booking_details (booking_id, transaction_type, booking_mode, bus_number, schedule_id, route_id, child, adult) VALUES (1012, 'Debit Card', 'C', 10, 231, 16, 1, 2);
INSERT INTO booking_details (booking_id, transaction_type, booking_mode, bus_number, schedule_id, route_id, child, adult) VALUES (1013, 'Cash', 'A', 5, 216, 17, 1, 3);
INSERT INTO booking_details (booking_id, transaction_type, booking_mode, bus_number, schedule_id, route_id, child, adult) VALUES (1014, 'Credit Card', 'C', 8, 228, 11, 2, 2);
INSERT INTO booking_details (booking_id, transaction_type, booking_mode, bus_number, schedule_id, route_id, child, adult) VALUES (1015, 'Paytm', 'C', 4, 213, 6, 2, 3);
INSERT INTO booking_details (booking_id, transaction_type, booking_mode, bus_number, schedule_id, route_id, child, adult) VALUES (1016, 'Cash', 'C', 1, 203, 3, 0, 3);
INSERT INTO booking_details (booking_id, transaction_type, booking_mode, bus_number, schedule_id, route_id, child, adult) VALUES (1017, 'Credit Card', 'A', 1, 202, 2, 1, 3);
INSERT INTO booking_details (booking_id, transaction_type, booking_mode, bus_number, schedule_id, route_id, child, adult) VALUES (1018, 'Debit Card', 'A', 9, 230, 14, 2, 3);
INSERT INTO booking_details (booking_id, transaction_type, booking_mode, bus_number, schedule_id, route_id, child, adult) VALUES (1019, 'Cash', 'A', 5, 218, 25, 2, 3);
INSERT INTO booking_details (booking_id, transaction_type, booking_mode, bus_number, schedule_id, route_id, child, adult) VALUES (1020, 'Paytm', 'C', 10, 231, 16, 0, 2);
INSERT INTO booking_details (booking_id, transaction_type, booking_mode, bus_number, schedule_id, route_id, child, adult) VALUES (1021, 'Cash', 'A', 5, 219, 27, 0, 3);
INSERT INTO booking_details (booking_id, transaction_type, booking_mode, bus_number, schedule_id, route_id, child, adult) VALUES (1022, 'Paytm', 'C', 9, 230, 14, 1, 3);
INSERT INTO booking_details (booking_id, transaction_type, booking_mode, bus_number, schedule_id, route_id, child, adult) VALUES (1023, 'Netbanking', 'A', 4, 213, 6, 0, 2);
INSERT INTO booking_details (booking_id, transaction_type, booking_mode, bus_number, schedule_id, route_id, child, adult) VALUES (1024, 'Credit Card', 'C', 7, 223, 7, 1, 2);
INSERT INTO booking_details (booking_id, transaction_type, booking_mode, bus_number, schedule_id, route_id, child, adult) VALUES (1025, 'Cash', 'C', 3, 212, 5, 0, 3);
INSERT INTO booking_details (booking_id, transaction_type, booking_mode, bus_number, schedule_id, route_id, child, adult) VALUES (1026, 'Debit Card', 'C', 6, 222, 8, 1, 2);
INSERT INTO booking_details (booking_id, transaction_type, booking_mode, bus_number, schedule_id, route_id, child, adult) VALUES (1027, 'Cash', 'A', 8, 228, 11, 0, 1);
INSERT INTO booking_details (booking_id, transaction_type, booking_mode, bus_number, schedule_id, route_id, child, adult) VALUES (1028, 'Credit Card', 'A', 5, 218, 25, 1, 2);
INSERT INTO booking_details (booking_id, transaction_type, booking_mode, bus_number, schedule_id, route_id, child, adult) VALUES (1029, 'Cash', 'A', 9, 292, 14, 0, 1);
INSERT INTO booking_details (booking_id, transaction_type, booking_mode, bus_number, schedule_id, route_id, child, adult) VALUES (1030, 'Cash', 'C', 8, 290, 11, 0, 3);
INSERT INTO booking_details (booking_id, transaction_type, booking_mode, bus_number, schedule_id, route_id, child, adult) VALUES (1031, 'Debit Card', 'A', 3, 269, 5, 1, 2);
INSERT INTO booking_details (booking_id, transaction_type, booking_mode, bus_number, schedule_id, route_id, child, adult) VALUES (1032, 'Paytm', 'A', 5, 279, 27, 1, 3);
INSERT INTO booking_details (booking_id, transaction_type, booking_mode, bus_number, schedule_id, route_id, child, adult) VALUES (1033, 'Debit Card', 'C', 10, 293, 16, 0, 1);
INSERT INTO booking_details (booking_id, transaction_type, booking_mode, bus_number, schedule_id, route_id, child, adult) VALUES (1034, 'Cash', 'A', 3, 269, 5, 0, 2);
INSERT INTO booking_details (booking_id, transaction_type, booking_mode, bus_number, schedule_id, route_id, child, adult) VALUES (1035, 'Credit Card', 'C', 5, 276, 17, 1, 2);
INSERT INTO booking_details (booking_id, transaction_type, booking_mode, bus_number, schedule_id, route_id, child, adult) VALUES (1036, 'Paytm', 'C', 7, 257, 24, 1, 2);
INSERT INTO booking_details (booking_id, transaction_type, booking_mode, bus_number, schedule_id, route_id, child, adult) VALUES (1037, 'Cash', 'C', 6, 254, 8, 1, 2);
INSERT INTO booking_details (booking_id, transaction_type, booking_mode, bus_number, schedule_id, route_id, child, adult) VALUES (1038, 'Credit Card', 'A', 8, 259, 11, 0, 2);
INSERT INTO booking_details (booking_id, transaction_type, booking_mode, bus_number, schedule_id, route_id, child, adult) VALUES (1039, 'Debit Card', 'A', 4, 242, 6, 0, 3);
INSERT INTO booking_details (booking_id, transaction_type, booking_mode, bus_number, schedule_id, route_id, child, adult) VALUES (1040, 'Cash', 'A', 2, 237, 22, 0, 2);
INSERT INTO booking_details (booking_id, transaction_type, booking_mode, bus_number, schedule_id, route_id, child, adult) VALUES (1041, 'Paytm', 'C', 5, 244, 13, 0, 3);
INSERT INTO booking_details (booking_id, transaction_type, booking_mode, bus_number, schedule_id, route_id, child, adult) VALUES (1042, 'Cash', 'A', 10, 231, 16, 0, 1);
INSERT INTO booking_details (booking_id, transaction_type, booking_mode, bus_number, schedule_id, route_id, child, adult) VALUES (1043, 'Netbanking', 'A', 4, 213, 6, 1, 2);
INSERT INTO booking_details (booking_id, transaction_type, booking_mode, bus_number, schedule_id, route_id, child, adult) VALUES (1044, 'Credit Card', 'C', 6, 221, 7, 1, 2);
INSERT INTO booking_details (booking_id, transaction_type, booking_mode, bus_number, schedule_id, route_id, child, adult) VALUES (1045, 'Cash', 'C', 2, 208, 18, 0, 3);
INSERT INTO booking_details (booking_id, transaction_type, booking_mode, bus_number, schedule_id, route_id, child, adult) VALUES (1046, 'Debit Card', 'C', 9, 292, 14, 1, 2);
INSERT INTO booking_details (booking_id, transaction_type, booking_mode, bus_number, schedule_id, route_id, child, adult) VALUES (1047, 'Cash', 'A', 5, 276, 17, 1, 2);
INSERT INTO booking_details (booking_id, transaction_type, booking_mode, bus_number, schedule_id, route_id, child, adult) VALUES (1048, 'Credit Card', 'A', 3, 269, 5, 0, 3);
INSERT INTO booking_details (booking_id, transaction_type, booking_mode, bus_number, schedule_id, route_id, child, adult) VALUES (1049, 'Cash', 'A', 6, 282, 7, 0, 3);
INSERT INTO booking_details (booking_id, transaction_type, booking_mode, bus_number, schedule_id, route_id, child, adult) VALUES (1050, 'Cash', 'C', 4, 273, 6, 0, 2);
